title: Open FileBot
description: O organizador de mídia definitivo, livre, comunitário e modernizado para Java 25.
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/wbaamaral/open-filebot
